DELETE http://localhost:3000/tweets/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIyNDkwMzg3fQ.qwYj4uLjRP23XHDH5dC17tgX5QnMy6muJY8A5Cln3_4


GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIyNDkwMzg3fQ.qwYj4uLjRP23XHDH5dC17tgX5QnMy6muJY8A5Cln3_4

POST http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIyNDkwMzg3fQ.qwYj4uLjRP23XHDH5dC17tgX5QnMy6muJY8A5Cln3_4
Content-Type: application/json 

{
   "tweet": "The Mornings..."
}

GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIyNDkwMzg3fQ.qwYj4uLjRP23XHDH5dC17tgX5QnMy6muJY8A5Cln3_4








POST http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}














